# _*_ Makefile _*_

shell: shell.c ls cat mkdir
	gcc -g shell.c -o shell

ls: ls.c
	gcc ls.c -o ls

cat: cat.c
	gcc cat.c -o cat

mkdir: mkdir.c
	gcc mkdir.c -o mkdir

clean:
	rm -f shell ls cat mkdir
