# _*_ Makefile _*_

all: dining-philosophers-a-1.c dining-philosophers-a-2.c dining-philosophers-b-1.c dining-philosophers-b-2.c
	gcc dining-philosophers-a-1.c -o dining-philosophers-a-1
	gcc dining-philosophers-a-2.c -o dining-philosophers-a-2
	gcc dining-philosophers-b-1.c -o dining-philosophers-b-1
	gcc dining-philosophers-b-2.c -o dining-philosophers-b-2

clean:
	rm -f dining-philosophers-a-1 dining-philosophers-a-2 dining-philosophers-b-1 dining-philosophers-b-2
